# Generated by Django 4.1.4 on 2022-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="desc",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
