# Generated by Django 4.1.4 on 2022-12-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_blogmodel_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogmodel",
            name="image",
        ),
    ]
