# Generated by Django 4.1.4 on 2022-12-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_commentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="created",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
